Added more weather commentary based on temperature Issue #14
M0nica/flask_weather pull request #52
Opened 2018-10-14 20:14 UTC by rushilShetty

Added more commentary based on how hot or cold the temperature is going to be

2018-10-21 21:27 UTC, M0nica commented on app.py
> +        weather_info = {'temperature': temperature, 'commentary': commentary}
```suggestion
        weather_info = {'temperature': temperature, 'commentary': rain_commentary}
```

2018-10-21 21:28 UTC, M0nica commented on app.py
> +        weather_info = {'temperature': temperature, 'commentary': rain_commentary}
Should this be commentary and not rain_commentary?

2018-10-21 21:28 UTC, M0nica requested changes
Thank you for this PR. I had a question but other than that it looks good to me.

2018-10-22 18:31 UTC, rushilShetty commented
Yes it should indeed be commentary and not rain commentary. Good find :)

2018-10-23 02:04 UTC, M0nica commented
@rushilShetty can you please update the commentary / rain commentary references? I do not have permission to edit your pull request? Once that is done we can merge 🎉

2020-06-29 01:33 UTC, closed without merging